stages:
  - lint
  - e2e
variables:
  DOCKER_HOST: tcp://docker:2375

golangci-lint:
  stage: lint
  artifacts:
    paths:
      - build
  image:
    name: golangci/golangci-lint:v1.21.0
    entrypoint: [ "" ]
  tags:
    - docker
  script:
    - go env
    - go mod verify
    - golangci-lint run -v --color always --timeout 120s
    - make build

lint-commit-msg:
  stage: lint
  image:
    name: haproxytech/check-commit:latest
    entrypoint: [ "" ]
  tags:
    - go
  script:
    - go run /check.go

.e2e:
  stage: e2e
  image:
    name: docker:stable
    entrypoint: [ "" ]
  services:
    - name: docker:18.09.7-dind
      alias: docker
  tags:
    - go
  before_script:
    - apk add git bash curl jq bats
  script:
    - bash -x ./e2e/run.bash

v21:
  extends: .e2e
  variables:
    LOCAL_IP_ADDRESS: docker
    HAPROXY_VERSION: "2.1"

v22:
  extends: .e2e
  variables:
    LOCAL_IP_ADDRESS: docker
    HAPROXY_VERSION: "2.2"

v23:
  extends: .e2e
  variables:
    LOCAL_IP_ADDRESS: docker
    HAPROXY_VERSION: "2.3"
