linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 42
  maligned:
    suggest-new: true
  dupl:
    threshold: 200
  goconst:
    min-len: 2
    min-occurrences: 2
  revive:
    rules:
    - name: var-naming
      severity: warning
      disabled: true
linters:
  enable-all: true
  disable:
    - dupl
    - exhaustive
    - exhaustivestruct
    - funlen
    - gci
    - gochecknoglobals
    - gocognit
    - goconst
    - gocyclo
    - godot
    - goerr113
    - gomnd
    - lll
    - nestif
    - nlreturn
    - wrapcheck
    - wsl
    - nakedret
    - paralleltest
    - testpackage
    - varnamelen
    - nosnakecase
    - exhaustruct
    - nonamedreturns
    - forcetypeassert
    - golint #deprecated
    - varcheck #deprecated
    - ifshort #deprecated
    - structcheck #deprecated
    - maligned #deprecated
    - scopelint #deprecated
    - interfacer #deprecated
    - deadcode #deprecated
    - rowserrcheck #rowserrcheck is disabled because of generics
    - sqlclosecheck #rowserrcheck is disabled because of generics
    - wastedassign #rowserrcheck is disabled because of generics

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "duplicate struct tag"
    - linters:
        - gosec
      text: "G[501]"

run:
  skip-dirs:
    - test
