name: Commit subject
on:
  pull_request:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: check-commit
        uses: docker://haproxytech/check-commit:v2.1.0
        env:
          API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
